version: "3.8"
services:
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: max
      MONGO_INITDB_ROOT_PASSWORD: secret
      # -MONGO_INITDB_ROOT_USERNAME= max    --> other option
      # -MONGO_INITDB_ROOT_USERNAME= secret --> other option
    # env_file:                             --> other option
    #   - ./env/mongo.env
    # networks:                             --> not needed because using docker-compose put all the services at the same network
    #   - goals-net 
  backend:
    build: ./backend
    # build:                                --> other option            
    #   context: ./backend  
    #   dockerfile: Dockerfile
    # container_name: backend                 --> force container name 
    ports:
      - '8080:80'
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend
volumes:
  data:
  logs: